# -*- coding: utf-8 -*-
"""Simple Task List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNOXN8OLB8dCz8fgUF3uBqeHIJY_JV6U
"""

class TaskManager:
    def __init__(self):
        self.tasks = []

    def add_task(self, description, priority=None):
        """Adds a new task to the list."""
        task = {"description": description, "priority": priority}
        self.tasks.append(task)
        print("Task added successfully!")

    def remove_task(self, index):
        """Removes a task from the list by its index."""
        if 0 <= index < len(self.tasks):
            del self.tasks[index]
            print("Task removed successfully!")
        else:
            print("Invalid index.")

    def list_tasks(self):
        """Prints all tasks in the list."""
        if self.tasks:
            for i, task in enumerate(self.tasks):
                priority_str = f" (Priority: {task['priority']})" if task['priority'] else ""
                print(f"{i+1}. {task['description']}{priority_str}")
        else:
            print("No tasks found.")

    def prioritize_task(self, index, priority):
        """Sets the priority of a task."""
        if 0 <= index < len(self.tasks):
            self.tasks[index]["priority"] = priority
            print("Priority updated successfully!")
        else:
            print("Invalid index.")

    def recommend_tasks(self, keywords):
        """Recommends tasks based on keywords in their descriptions."""
        recommendations = []
        for task in self.tasks:
            if any(keyword in task["description"].lower() for keyword in keywords.lower().split()):
                recommendations.append(task)
        return recommendations

if __name__ == "__main__":
    manager = TaskManager()

    while True:
        print("\nTask Manager Menu:")
        print("1. Add Task")
        print("2. Remove Task")
        print("3. List Tasks")
        print("4. Prioritize Task")
        print("5. Recommend Tasks")
        print("6. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            description = input("Enter task description: ")
            priority = input("Enter priority (optional): ") or None
            manager.add_task(description, priority)

        elif choice == '2':
            manager.list_tasks()
            index = int(input("Enter index of task to remove: ")) - 1
            manager.remove_task(index)

        elif choice == '3':
            manager.list_tasks()

        elif choice == '4':
            manager.list_tasks()
            index = int(input("Enter index of task to prioritize: ")) - 1
            priority = input("Enter priority: ")
            manager.prioritize_task(index, priority)

        elif choice == '5':
            keywords = input("Enter keywords to search for: ")
            recommendations = manager.recommend_tasks(keywords)
            if recommendations:
                print("\nRecommended Tasks:")
                for task in recommendations:
                    print(f"- {task['description']}")
            else:
                print("No matching tasks found.")

        elif choice == '6':
            print("Exiting Task Manager.")
            break

        else:
            print("Invalid choice. Please try again.")